name: CI with Approval

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    steps:
      - name: Request Approval
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.APPROVAL_TOKEN }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.sha,
            });

            if (pullRequests.length === 0) {
              console.log("No pull request found.");
              return;
            }

            const pullRequestNumber = pullRequests[0].number;

            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber,
              event: 'APPROVE',
              body: 'Please review and approve.',
              reviewers: ['ktpl-harpal']
            });

  build:
    runs-on: ubuntu-latest
    needs: approval
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
