name: CI with Approval

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  wait-for-approval:
    name: Wait_for_approval Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for approval
        uses: arun291091/wait_for_approval_gha@v1
        with:
          base_repository_branch: main
          github_org: ktpl-harpal
          repository_name: test-repo
          pr_reviewer: ktpl-hemang
          time_limit: 300
          github_token: ${{ secrets.GIT_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && needs.wait-for-approval.outputs.approved == 'true')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
