name: CI with Approval

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  wait-for-approval:
    name: Wait for approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for manual approval
        uses: your-github-user/manual-approval@your-dev-branch
        with:
          secret: ${{ secrets.APPROVAL_TOKEN }}
          approvers: ktpl-hemang

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: wait-for-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
