name: CI with Approval

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  wait-for-approval:
    name: Wait for approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Here you can add any necessary steps to prepare your codebase for manual approval
      # For example, running tests, linting, etc.

      - name: Request review from ktpl-hemang
        if: github.event_name == 'pull_request'
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
          -d '{"reviewers":["ktpl-hemang"],"team_reviewers":[],"labels":[],"reviewers":[],"assignees":[]}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers"

      - name: Wait for manual approval
        if: github.event_name == 'push'
        run: echo "::set-output name=approved::true" # Simulating approval for push events

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && needs.wait-for-approval.outputs.approved == 'true')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
