name: CI with Approval

on:
  push:
    branches:
      - master

jobs:
  wait-for-approval:
    name: Wait_for_approval Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for approval
        id: approval
        uses: arun291091/wait_for_approval_gha@v1
        with:
          base_repository_branch: main
          github_org: ktpl-harpal
          repository_name: testrepo
          pr_reviewer: ktpl-hemang
          time_limit: 300
          github_token: ${{ secrets.GIT_TOKEN }}
      - name: Set approval status
        run: echo "Approval status: ${{ steps.approval.outputs.approved }}"
      - name: Set PR URL
        if: steps.approval.outputs.approved == 'true'
        run: echo "::set-output name=pr_url::${{ steps.approval.outputs.pull_request_url }}"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.wait-for-approval.outputs.approved == 'true'
    steps:
      - name: Debug approval status
        run: echo "Approval status: ${{ needs.wait-for-approval.outputs.approved }}"
      - name: Debug PR URL
        run: echo "PR URL: ${{ needs.wait-for-approval.outputs.pr_url }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
